import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import SwiperCore from 'swiper';
import { Navigation } from "swiper/modules";
import SessionProvider from "./session-provider";
import { getSession } from "@/utils/session";

SwiperCore.use([Navigation])

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider provider={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
